# Generated by Django 4.2.1 on 2023-05-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images')),
                ('thumbnail', models.ImageField(null=True, upload_to='products/thumbnails')),
                ('small', models.ImageField(null=True, upload_to='products/small')),
                ('large', models.ImageField(null=True, upload_to='products/large')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='products', to='products.productimage'),
        ),
    ]
